export { capability } from './capability.js';
export {
  buildDocumentOptimizerConfig,
  documentOptimizerConfigDefaults,
  documentOptimizerConfigSpec,
  documentOptimizerEnvSchema,
  loadDocumentOptimizerConfig,
  type DocumentOptimizerConfig,
  type DocumentOptimizerEnv,
  type DocumentOptimizerLimits,
} from './config.js';
export {
  documentIdSchema,
  documentManifestSchema,
  documentPackageSchemaVersion,
  figureDescriptorSchema,
  optimizedDocumentPackageSchema,
  optimizerPipelineVersion,
  outlineEntrySchema,
  processingStatusSchema,
  provenanceSchema,
  sectionRecordSchema,
  sourceFormatSchema,
  tableRecordSchema,
  type DocumentManifest,
  type DocumentMetadata,
  type DocumentMetrics,
  type DocumentProvenance,
  type DocumentSummary,
  type FigureDescriptor,
  type OptimizedDocumentPackage,
  type OutlineEntry,
  type ProcessingStatus,
  type SectionRecord,
  type SourceFormat,
  type TableRecord,
} from './domain/model.js';
export { capabilityManifest } from './manifest.js';
export { type CapabilityServices } from './services.js';
export {
  capabilityTools,
  getDocumentFigureTool,
  getDocumentOutlineTool,
  getDocumentSectionTool,
  getDocumentTableTool,
  inspectDocumentTool,
  optimizeDocumentTool,
  type GetDocumentFigureInput,
  type GetDocumentFigureOutput,
  type GetDocumentOutlineInput,
  type GetDocumentOutlineOutput,
  type GetDocumentSectionInput,
  type GetDocumentSectionOutput,
  type GetDocumentTableInput,
  type GetDocumentTableOutput,
  type InspectDocumentInput,
  type InspectDocumentOutput,
  type OptimizeDocumentInput,
  type OptimizeDocumentOutput,
} from './tools/definitions.js';
